apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistics-service
  namespace: supply-us
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logistics-service
  template:
    metadata:
      labels:
        app: logistics-service
    spec:
      containers:
      - name: logistics-service
        image: <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/logistics-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key-secret
              key: api-key
