apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-ui
  namespace: supply-us
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracking-ui
  template:
    metadata:
      labels:
        app: tracking-ui
    spec:
      containers:
      - name: tracking-ui
        image: <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/tracking-ui:latest
        ports:
        - containerPort: 8000
        env:
        - name: LOGISTICS_SERVICE_URL
          value: "http://logistics-service.supply-us.svc.cluster.local:5000"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key-secret
              key: api-key
