AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch alarm for non-compliant AWS Config rules. Set SNS_TOPIC_ARN before deployment.
Resources:
  ConfigRuleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm for non-compliant AWS Config rules"
      Namespace: AWS/Config
      MetricName: NonCompliantResources
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - '{{SNS_TOPIC_ARN}}'  # Replace with your SNS Topic ARN
