apiVersion: apps/v1
kind: Deployment
metadata:
  name: encoder-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encoder-frontend
  template:
    metadata:
      labels:
        app: encoder-frontend
    spec:
      containers:
      - name: encoder-frontend
        image: encoder-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: encoder-frontend-service
spec:
  selector:
    app: encoder-frontend
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
